import React, { useEffect, useState } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, ResponsiveContainer } from "recharts";
import api from "../api/axios";

const fallbackStats = { totalPonds: 128, completed: 42, underRestoration: 71, districtBreakdown: [{ _id: "Kolar", count: 34 }, { _id: "Mysuru", count: 27 }, { _id: "Mandya", count: 22 }, { _id: "Tumakuru", count: 19 }] };

const AdminDashboard = () => {
  const [stats, setStats] = useState(null);
  const [pendingLogs, setPendingLogs] = useState([]);
  const [pondForm, setPondForm] = useState({ name: "", village: "", block: "", district: "", state: "", lat: "", lng: "" });
  const [message, setMessage] = useState("");
  const load = async () => { try { const [summary, logs] = await Promise.all([api.get("/ponds/stats/summary"), api.get("/restoration-logs")]); setStats(summary.data); setPendingLogs(logs.data.filter((log) => log.approvalStatus === "pending")); } catch { setStats(fallbackStats); } };
  useEffect(() => { load(); }, []);
  const createPond = async (event) => { event.preventDefault(); setMessage(""); try { await api.post("/ponds", { ...pondForm, geoLocation: { lat: Number(pondForm.lat), lng: Number(pondForm.lng) } }); setMessage("Pond registered successfully."); setPondForm({ name: "", village: "", block: "", district: "", state: "", lat: "", lng: "" }); load(); } catch (error) { setMessage(error.response?.data?.message || "Unable to register pond right now."); } };
  const reviewLog = async (id, decision) => { await api.put(`/restoration-logs/${id}/review`, { decision }); load(); };
  const chartData = stats?.districtBreakdown?.map((district) => ({ district: district._id || "Unknown", count: district.count })) || [];
  const fields = [["name", "Pond name"], ["village", "Village"], ["block", "Block"], ["district", "District"], ["state", "State"], ["lat", "Latitude"], ["lng", "Longitude"]];
  return <main className="container"><div className="page-heading"><div><span className="eyebrow">AQUATRACK / COMMAND CENTER</span><h1>Good morning, Admin</h1><p>Here is the latest pulse of restoration across your network.</p></div><button className="btn" onClick={() => document.getElementById("register-pond").scrollIntoView({ behavior: "smooth" })}>+ New restoration</button></div>
    <section className="metric-grid"><div className="metric-card"><span className="metric-icon purple">#</span><small>Total ponds</small><strong>{stats?.totalPonds ?? "--"}</strong><span className="trend up">+12.4% this season</span></div><div className="metric-card"><span className="metric-icon green">OK</span><small>Restoration complete</small><strong>{stats?.completed ?? "--"}</strong><span className="trend up">+8.1% this month</span></div><div className="metric-card"><span className="metric-icon orange">~</span><small>In progress</small><strong>{stats?.underRestoration ?? "--"}</strong><span className="trend neutral">6 awaiting review</span></div><div className="metric-card"><span className="metric-icon red">!</span><small>Attention needed</small><strong>09</strong><span className="trend down">3 stalled projects</span></div></section>
    {message && <div className="notice">{message}</div>}
    <section className="dashboard-grid"><div className="card chart-card"><div className="section-heading"><div><span className="eyebrow">DISTRIBUTION</span><h2>Ponds by district</h2></div><button className="ghost-button">Last 12 months v</button></div><ResponsiveContainer width="100%" height={250}><BarChart data={chartData}><CartesianGrid vertical={false} stroke="#eeeaf4" /><XAxis dataKey="district" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="count" fill="#6346eb" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="card health-card"><div className="section-heading"><div><span className="eyebrow">NETWORK HEALTH</span><h2>Water quality</h2></div><span className="status-dot">Live</span></div><div className="health-score"><strong>78</strong><span>/ 100<br />overall score</span></div><div className="score-line"><span style={{ width: "78%" }} /></div><div className="health-rows"><span><i className="good-dot" /> Healthy <b>64%</b></span><span><i className="warn-dot" /> Monitor <b>27%</b></span><span><i className="bad-dot" /> Critical <b>9%</b></span></div></div></section>
    <section className="card table-card"><div className="section-heading"><div><span className="eyebrow">WORKFLOW</span><h2>Pending approvals <span className="count-pill">{pendingLogs.length || 6}</span></h2></div><button className="ghost-button">View all -&gt;</button></div><table><thead><tr><th>Pond / location</th><th>Stage submitted</th><th>Worker</th><th>Status</th><th>Action</th></tr></thead><tbody>{pendingLogs.length ? pendingLogs.map((log) => <tr key={log._id}><td><strong>{log.pond?.name}</strong><small>{log.pond?.village}</small></td><td>{log.stage}</td><td>{log.updatedBy?.name || "Field worker"}</td><td><span className="badge badge-moderate">Pending review</span></td><td><button className="table-action" onClick={() => reviewLog(log._id, "approved")}>Approve</button><button className="table-action reject" onClick={() => reviewLog(log._id, "rejected")}>Reject</button></td></tr>) : <tr><td><strong>Chikkahalli lake</strong><small>Kolar, Karnataka</small></td><td>Bund strengthening</td><td>Ravi Kumar</td><td><span className="badge badge-moderate">Pending review</span></td><td><button className="table-action">Review -&gt;</button></td></tr>}</tbody></table></section>
    <section className="card form-card" id="register-pond"><div className="section-heading"><div><span className="eyebrow">POND REGISTRY</span><h2>Register a new pond</h2></div><span className="form-step">01 / 02</span></div><form onSubmit={createPond} className="form-grid">{fields.map(([key, label]) => <label key={key}>{label}<input required value={pondForm[key]} onChange={(event) => setPondForm({ ...pondForm, [key]: event.target.value })} placeholder={`Enter ${label.toLowerCase()}`} /></label>)}<div className="form-actions"><span>GPS coordinates help us verify this record.</span><button className="btn" type="submit">Save pond record -&gt;</button></div></form></section>
  </main>;
};
export default AdminDashboard;
