import React, { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api from "../api/axios";

const fallbackPonds = [
  { pondId: "POND-0042", name: "Chikkahalli Lake", district: "Kolar", village: "Chikkahalli", currentStage: "desilting", overallHealthScore: "good", budgetAllocated: 850000, budgetUtilized: 390000 },
  { pondId: "POND-0057", name: "Hulikunte Kere", district: "Tumakuru", village: "Hulikunte", currentStage: "bund_strengthening", overallHealthScore: "moderate", budgetAllocated: 620000, budgetUtilized: 550000 },
  { pondId: "POND-0061", name: "Dodda Katte", district: "Mysuru", village: "Belur", currentStage: "plantation", overallHealthScore: "poor", budgetAllocated: 440000, budgetUtilized: 196000 },
];

const pages = {
  ponds: ["Pond registry", "Register, verify and manage every water body", "Register pond", "Bulk import", "Duplicate check"],
  approvals: ["Approval queue", "Review field evidence, stage completion and e-signatures", "Pending updates", "Stalled projects", "Workflow"],
  map: ["Map dashboard", "Live network view with colour-coded pond health", "Health markers", "GPS verification", "Coverage"],
  budget: ["Funds & resources", "Track allocation, utilization and field resources", "Scheme funds", "Resource log", "Variance alerts"],
  analytics: ["Analytics & benchmarking", "District, block and village restoration intelligence", "District view", "Seasonal trends", "Leaderboard"],
  reports: ["Report builder", "Create compliance, CSR and public transparency reports", "PDF export", "Excel export", "Impact certificates"],
  community: ["Citizen reports", "Moderate feedback, water-level reports and adoption requests", "Moderation queue", "Adopt a pond", "Announcements"],
  workers: ["Workers & agencies", "Manage assignments, checklists and partner performance", "Worker approvals", "Assignments", "Contractors"],
  audit: ["System activity", "RTI-ready history of changes and administration", "Pond history", "Audit export", "Access events"],
};
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const stage = (value) => (value || "identified").replaceAll("_", " ");

export default function AdminWorkspace() {
  const { section = "ponds" } = useParams();
  const [ponds, setPonds] = useState(fallbackPonds);
  const [query, setQuery] = useState("");
  const [notice, setNotice] = useState("");
  const config = pages[section] || pages.ponds;
  useEffect(() => { api.get("/ponds").then(({ data }) => data.length && setPonds(data)).catch(() => {}); }, [section]);
  const visible = useMemo(() => ponds.filter((pond) => `${pond.name} ${pond.pondId} ${pond.district}`.toLowerCase().includes(query.toLowerCase())), [ponds, query]);
  const action = (label) => setNotice(`${label} is ready to be connected to the selected record.`);
  const districtData = Object.values(ponds.reduce((all, pond) => { const key = pond.district || "Unassigned"; all[key] = all[key] || { district: key, ponds: 0 }; all[key].ponds += 1; return all; }, {}));
  const healthData = ["good", "moderate", "poor"].map((name) => ({ name, value: ponds.filter((pond) => pond.overallHealthScore === name).length || 1 }));
  return <main className="container workspace"><div className="page-heading"><div><span className="eyebrow">AQUATRACK / ADMIN WORKSPACE</span><h1>{config[0]}</h1><p>{config[1]}</p></div><button className="btn" onClick={() => action(config[2])}>+ {config[2]}</button></div>{notice && <div className="notice">{notice}</div>}<div className="workspace-tabs">{config.slice(2).map((item, i) => <button className={i ? "" : "selected"} key={item} onClick={() => action(item)}>{item}</button>)}</div>{section === "map" ? <MapPanel ponds={visible} /> : section === "analytics" ? <AnalyticsPanel districts={districtData} health={healthData} /> : section === "reports" ? <ReportsPanel action={action} /> : section === "approvals" ? <ApprovalsPanel action={action} /> : section === "audit" ? <AuditPanel /> : <Registry section={section} ponds={visible} query={query} setQuery={setQuery} action={action} />}</main>;
}

function Registry({ section, ponds, query, setQuery, action }) { const budget = section === "budget"; const community = section === "community"; const workers = section === "workers"; return <><section className="metric-grid"><Metric label="Records in view" value={ponds.length} tone="purple" /><Metric label={budget ? "Allocated funds" : "Healthy ponds"} value={budget ? money(ponds.reduce((sum, p) => sum + (p.budgetAllocated || 0), 0)) : ponds.filter((p) => p.overallHealthScore === "good").length} tone="green" /><Metric label={community ? "Pending moderation" : "Needs attention"} value={community ? 12 : ponds.filter((p) => p.overallHealthScore === "poor").length} tone="orange" /><Metric label="Live status" value="Synced" tone="red" /></section><section className="card table-card"><div className="section-heading"><div><span className="eyebrow">MANAGEMENT TABLE</span><h2>{community ? "Community submissions" : workers ? "Assignments and agency coverage" : "Network records"}</h2></div><input className="table-search" placeholder="Search records" value={query} onChange={(e) => setQuery(e.target.value)} /></div><table><thead><tr><th>Pond / record</th><th>{budget ? "Allocated" : workers ? "Assignment" : community ? "Type" : "Location"}</th><th>{budget ? "Utilized" : workers ? "Checklist" : community ? "Status" : "Stage"}</th><th>{budget ? "Variance" : workers ? "Status" : community ? "Action" : "Health"}</th><th /></tr></thead><tbody>{ponds.map((p) => <tr key={p._id || p.pondId}><td><strong>{p.name}</strong><small>{p.pondId} · {p.district}</small></td>{budget ? <><td>{money(p.budgetAllocated)}</td><td>{money(p.budgetUtilized)}</td><td><span className="badge badge-good">{money((p.budgetAllocated || 0) - (p.budgetUtilized || 0))}</span></td></> : workers ? <><td>{p.assignedWorker?.name || "Unassigned"}</td><td>3 of 5 complete</td><td><span className="badge badge-moderate">Review</span></td></> : community ? <><td>Feedback</td><td><span className="badge badge-moderate">Pending review</span></td><td><button className="table-action" onClick={() => action("Moderation review")}>Review</button></td></> : <><td>{p.village}, {p.district}</td><td className="capitalize">{stage(p.currentStage)}</td><td><span className={`badge badge-${p.overallHealthScore === "good" ? "good" : p.overallHealthScore === "poor" ? "poor" : "moderate"}`}>{p.overallHealthScore || "unknown"}</span></td></>}<td><button className="table-action" onClick={() => action("Record details")}>Open</button></td></tr>)}</tbody></table></section></>; }
function ApprovalsPanel({ action }) { return <section className="approval-layout"><div className="card"><span className="eyebrow">STALLED PROJECT ALERT</span><h2>3 projects need a decision</h2><p className="muted">No worker update has been received for more than 14 days.</p>{["Chikkahalli Lake · Bund strengthening", "Dodda Katte · Plantation", "Mavina Kere · Desilting"].map((item) => <button className="approval-item" key={item} onClick={() => action("Evidence review")}>{item}<span>Review →</span></button>)}</div><div className="card review-card"><span className="eyebrow">STAGE REVIEW</span><h2>Evidence and sign-off</h2><div className="photo-placeholders"><div>Before</div><div>During</div><div>After</div></div><textarea placeholder="Approval remarks or voice-to-text note" rows="4" /><div className="button-row"><button className="table-action reject" onClick={() => action("Rejection")}>Reject</button><button className="btn" onClick={() => action("Approval")}>Approve stage</button></div></div></section>; }
function MapPanel({ ponds }) { return <><section className="card map-canvas"><div className="map-grid" />{ponds.map((p, i) => <button className={`map-pin ${p.overallHealthScore || "unknown"}`} style={{ left: `${20 + i * 25}%`, top: `${30 + (i % 2) * 28}%` }} key={p.pondId}>●</button>)}<div className="map-legend"><b>Live pond health</b><span>● Good</span><span>● Moderate</span><span>● Poor</span></div></section><section className="card"><span className="eyebrow">GPS & DUPLICATE CHECK</span><h2>Map-pinned pond records</h2><p className="muted">Worker registrations record GPS coordinates. Nearby coordinates are flagged for duplicate review before approval.</p></section></>; }
function AnalyticsPanel({ districts, health }) { return <div className="dashboard-grid"><section className="card chart-card"><span className="eyebrow">DISTRICT COMPARISON</span><h2>Ponds by district</h2><ResponsiveContainer width="100%" height={260}><BarChart data={districts}><CartesianGrid vertical={false} /><XAxis dataKey="district" /><YAxis /><Tooltip /><Bar dataKey="ponds" fill="#6346eb" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></section><section className="card chart-card"><span className="eyebrow">WATER HEALTH</span><h2>Network condition</h2><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={health} dataKey="value" nameKey="name" outerRadius={90} fill="#6346eb" label /><Tooltip /></PieChart></ResponsiveContainer></section><section className="card chart-card full-span"><span className="eyebrow">SEASONAL PROJECTION</span><h2>Restoration and water-level trend</h2><ResponsiveContainer width="100%" height={240}><LineChart data={[{ month: "Jan", score: 61 }, { month: "Mar", score: 67 }, { month: "Jun", score: 73 }, { month: "Aug", score: 78 }, { month: "Oct", score: 82 }]}><CartesianGrid vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="score" stroke="#6346eb" strokeWidth={3} /></LineChart></ResponsiveContainer></section></div>; }
function ReportsPanel({ action }) { return <section className="report-grid">{[["District progress report", "PDF / Excel"], ["Impact certificate", "PDF"], ["RTI data export", "Excel / CSV"], ["Custom report canvas", "Build"]].map(([name, type]) => <article className="card report-card" key={name}><span className="report-type">{type}</span><h2>{name}</h2><p className="muted">Generate a structured, shareable report using current pond records.</p><button className="table-action" onClick={() => action(name)}>Configure export →</button></article>)}</section>; }
function AuditPanel() { return <section className="card table-card"><span className="eyebrow">IMMUTABLE ACTIVITY HISTORY</span><h2>System-wide activity</h2><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Record</th></tr></thead><tbody>{[["Today, 10:42", "Ravi Kumar", "Submitted quality reading", "Chikkahalli Lake"], ["Today, 09:15", "Admin", "Approved restoration stage", "Hulikunte Kere"], ["Yesterday", "Meena S", "Filed citizen feedback", "Dodda Katte"]].map((row) => <tr key={row.join("-")}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></section>; }
function Metric({ label, value, tone }) { return <div className="metric-card"><span className={`metric-icon ${tone}`}>●</span><small>{label}</small><strong>{value}</strong><span className="trend neutral">Updated just now</span></div>; }
